### ISSUE TITLE
Why is the router added to StaticPagesAction?

### ISSUE THREAD

**Issue by froschdesign** [zfmastery/ze-static-pages#2]
The `router` property is used only in constructor.

https://github.com/zfmastery/ze-static-pages/blob/master/src/Action/StaticPagesAction.php#L34

**Comment by settermjd** [comment]
Thanks for spotting that and creating an issue. #3 has been merged, removing @router.

**Comment by froschdesign** [comment]
No problem. Thanks for the quick response and for sharing this module!
